server:
  port: 8000

spring:

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5435/postgres
    password: postgres
    username: postgres

  jpa:
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    show-sql: true
    properties:
      hibernate:
        hbm2ddl:
          auto: validate
        format_sql: true

  ldap:
    urls: ldap://localhost:5389
    base: dc=spring-ldap,dc=com
    username: cn=admin,dc=spring-ldap,dc=com
    password: password

  liquibase:
    enabled: true
    default-schema: public
    change-log: classpath:db/migration/changelog.yml

springdoc:
  swagger-ui:
    enabled: true