server:
  port: 8000

spring:

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5435/postgres
    password: postgres
    username: postgres

  jpa:
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    show-sql: true
    properties:
      hibernate:
        hbm2ddl:
          auto: validate
        format_sql: true

  ldap:
    urls: ldap://localhost:5389
    base: dc=spring-ldap,dc=com
    username: cn=admin,dc=spring-ldap,dc=com
    password: password
#    embedded:
##      validation:
##        schema: classpath:ldap/default.schema
#      ldif: classpath:ldap/ldif/embedded/embedded.ldif
#      base-dn: dc=springframework,dc=org
#      credential:
#        username: uid=ben,ou=people
#        password: $2a$10$c6bSeWPhg06xB1lvmaWNNe4NROmZiSpYhlocU/98HNr2MhIOiSt36
#      port: 5389

  liquibase:
    enabled: true
    default-schema: public
    change-log: classpath:db/migration/changelog.yml

springdoc:
  swagger-ui:
    enabled: true

logging:
  level:
    root: info